# Generated by Django 6.0.1 on 2026-02-05 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('new', 'New'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='new', max_length=20)),
                ('total_qty', models.PositiveIntegerField(default=0)),
                ('total_sum', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=500)),
                ('color_id', models.PositiveIntegerField(blank=True, null=True)),
                ('color_name', models.CharField(blank=True, max_length=120, null=True)),
                ('qty', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('total', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
        ),
    ]
