# Generated by Django 6.0.1 on 2026-02-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gnizdechko_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_special',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
