# Generated by Django 6.0.1 on 2026-02-03 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gnizdechko_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='main_image',
            field=models.ImageField(default='categories/default.jpg', upload_to='categories/'),
        ),
    ]
