# Generated by Django 6.0.1 on 2026-02-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gnizdechko_app', '0002_category_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
