# Generated by Django 6.0.1 on 2026-02-09 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gnizdechko_app', '0002_product_is_special'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='main_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='main_products', to='gnizdechko_app.category'),
            preserve_default=False,
        ),
    ]
